### ISSUE TITLE
Error with getting info of a playlist with removed video

### ISSUE THREAD

**Issue by UnacceptableUse** [fent/node-youtube-dl#100]
Trying to get video info for a video that has been removed throws an error without providing info on the other videos.

Here's some code to reproduce it:  
 
```javascript
var youtubedl = require('youtube-dl');

var video = youtubedl("https://www.youtube.com/playlist?list=PLK9VXBuA-HyUk9gmJqphOcezwBS8lufpL", [
    "--audio-quality=48000",
    "--force-ipv4",
    "--default-search=ytsearch",
    "--no-playlist"], {cwd: __dirname});
video.on('info', function (info) {
    console.log(info);
});
```

EDIT: Happy 100th issue

**Comment by przemyslawpluta** [comment]
@UnacceptableUse try latest master it should be sorted. Let me know ...

**Comment by UnacceptableUse** [comment]
Confirmed fixed. Thanks!

**Comment by UnacceptableUse** [comment]
Looks like "Please sign in to view this video" is another error that it fails on"

**Comment by przemyslawpluta** [comment]
@UnacceptableUse link?

**Comment by przemyslawpluta** [comment]
@UnacceptableUse again try latest master ...
