### ISSUE TITLE
youtube-dl binary permissions set too strict

### ISSUE THREAD

**Issue by nielslaukens** [fent/node-youtube-dl#102]
Why are the permissions of the `youtube-dl` binary explicitly restricted? (https://github.com/fent/node-youtube-dl/blob/a6d6d3610d850aa34f24fe40d059ea7c9cecdefd/lib/downloader.js#L26). This results on my system with a file mode of 0711.

This causes the binary to be unusable by any other user than the one that owns the file with the following error, since Python needs to READ the file in order to execute it.
`python: can't open file '/path/to/project/node_modules/youtube-dl/bin/youtube-dl': [Errno 13] Permission denied`

**Comment by przemyslawpluta** [comment]
@nielslaukens what would you expect?

**Comment by nielslaukens** [comment]
@przemyslawpluta I would expect the standard 0755 permissions on an executable (i.e. mask 0022 or 18 in decimal form)

**Comment by przemyslawpluta** [comment]
@nielslaukens try latest master

**Comment by EnKrypt** [comment]
This is not fixed. Please reopen this issue.

A [current project of mine](https://github.com/EnKrypt/Botato) uses youtube-dl as a dependency in a global install, and there is no way to get it running without changing the permissions of the youtube-dl binary manually to 755. (It is installed with 711)

This is a minimalistic project and the extra chmod in the installation step looks very dirty and unnecessary.
