### ISSUE TITLE
Extract video/audio URL only

### ISSUE THREAD

**Issue by goldani** [fent/node-youtube-dl#104]
I'm trying to extract the URL of the audio for a video. This is how I'm doing it currently, but it isn't that efficient for my purposes:
```
ytdl.getInfo(videoURL, [], function(err, info){
    if (err) throw err
    var audioURL = info.formats[0].url
```
I've also tried calling the youtube-dl binary directly, but it ends up downloading the video regardless of the options being passed:
```
ytdl.exec(videoURL, ['-g'], {}, function(err, output) {
    if (err) throw err
    console.log(output.join('\n')) // shows the progress of the download
})
```
In the above case, the '-g' option should force youtube-dl to print the two URLs.

**Comment by przemyslawpluta** [comment]
@goldani what's the `videoURL` ?

**Comment by goldani** [comment]
Right, videoURL is just the string of any Youtube video link.

**Comment by przemyslawpluta** [comment]
@goldani is this what you're looking for [formats](https://github.com/fent/node-youtube-dl/blob/master/example/formats.js)

**Comment by przemyslawpluta** [comment]
@goldani try latest git master it should work fine now:

```js
ytdl.exec(videoURL, ['-g'], {}, function exec(err, output) {
    if (err) { return err.stack; }
    console.log(output.join('\n'))
});
```

**Comment by goldani** [comment]
I'll close this issue and try it out soon. If there's still a problem I'll reopen it. Thank you for your help.
