### ISSUE TITLE
Can’t npm install youtube-dl on Mac yosemite 10.10.1

### ISSUE THREAD

**Issue by wokuang** [fent/node-youtube-dl#52]
execute command and error message list below.

```
$  npm -v
2.1.17

$  node -v
v0.10.35

$   npm install youtube-dl
-
> youtube-dl@1.6.0 preinstall /Users/taian/tmp/node_modules/youtube-dl
> node ./scripts/download.js

Downloading latest youtube-dl

/Users/taian/tmp/node_modules/youtube-dl/scripts/download.js:19
  throw err;
        ^
Error: CERT_UNTRUSTED
    at SecurePair.<anonymous> (tls.js:1381:32)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:980:10)
    at CleartextStream.read [as _read] (tls.js:472:13)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "youtube-dl"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.17
npm ERR! code ELIFECYCLE

npm ERR! youtube-dl@1.6.0 preinstall: `node ./scripts/download.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the youtube-dl@1.6.0 preinstall script 'node ./scripts/download.js'.
npm ERR! This is most likely a problem with the youtube-dl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/download.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls youtube-dl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/taian/tmp/npm-debug.log
```

**Comment by fent** [comment]
Not sure why this would happen, it works for me when I install it or run the `scripts/download.js` script.

Try some of the solutions here

http://stackoverflow.com/questions/21855035/ssl-error-cert-untrusted-while-using-npm-command

**Comment by fent** [comment]
update?

**Comment by Subha** [comment]
I am opening this issue as I am facing some error in installing the youtube-dl

Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at TCP.onread (net.js:559:19)

npm ERR! youtube-dl@1.10.5 preinstall: `node ./scripts/download.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the youtube-dl@1.10.5 preinstall script.
npm ERR! This is most likely a problem with the youtube-dl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/download.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls youtube-dl
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "youtube-dl"

Any help is really appreciated.

**Comment by fent** [comment]
Can you try again? Might have been a temporary error

**Comment by Subha** [comment]
Thank you for your response. Still it did not work. I am getting ConnectionReset error when "Downloading latest youtube-dl" starts.

**Comment by fent** [comment]
:/

Downloading the latest binary works for me. Deleting the current one in the `bin` folder and redownloading also works. Can you test if it works on another computer?
