### ISSUE TITLE
Any reason duration is not available from getInfo()?

### ISSUE THREAD

**Issue by tifroz** [fent/node-youtube-dl#53]
Looking at the source code there is a comment stating  "*Arguments we dont want users to use with youtube-dl because they will break the module*" and the code proceeds to exclude the `--get-duration` argument.

I did a quick test using *http://vimeo.com/channels/staffpicks/115680769*, and the duration was actually returned ok (though the corresponding string `9:56` is later mis-categorized as `filename` in the result hash)

I would submit a PR to allow the duration among the allowable arguments (and categorize the results appropriately) - but I figured I would check first in case there is something I am missing: I only tested with this one URL after all.

**Comment by fent** [comment]
Ah, those cli options are excluded, but they are still used when `getInfo()` is called

https://github.com/fent/node-youtube-dl/blob/master/lib/youtube-dl.js#L204

but you're right, the `--get-duration` argument should be added to that too. I'll add it later tonight and do some testing.
