### ISSUE TITLE
--extract-audio

### ISSUE THREAD

**Issue by tejasmanohar** [fent/node-youtube-dl#57]
how do we use `--extract-audio` option that exists in `youtube-dl`?

**Comment by fent** [comment]
It doesn't support any post processing options since it uses the `--get-url` option to get the url and then create a request for it in node.

You can use ffmpeg to extract the audio, try a module for it like [fluent-ffmpeg](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg).
