### ISSUE TITLE
--format=bestvideo+bestaudio is not working

### ISSUE THREAD

**Issue by jfarribillaga** [fent/node-youtube-dl#63]
If we use bestvideo+bestaudio directly using youtube-dl command line, video and audio are merged (if you have ffmpeg installed).

Often used for DASH youtube videos (1080p)

**Comment by fent** [comment]
Oh yeah this doesn't use the post processing features of youtube-dl, it just gets the download url from it. this allows us to use a node stream to download the video.

You can use ffmpeg with one of these

https://www.npmjs.com/search?q=ffmpeg
