### ISSUE TITLE
Remove check platform.

### ISSUE THREAD

**Issue by phongdaohp** [fent/node-youtube-dl#66]
Dear Developer.

I check your code I saw line code check platform "isWin", I think it is unnecessary because your module can working in linux platform but when I install in linux I must fix your code to compatible. 

Can you remove this lines below in next version?

// Check if win.
var isWin = /^win/.test(process.platform);
if (isWin) { opt = [process.env.PYTHON || 'python', [file].concat(args)]; }

and change it to 

opt = [process.env.PYTHON || 'python', [file].concat(args)];

Best regard.

Phong Dao

**Comment by prabhu** [comment]
Can you send a PR?

**Comment by phongdaohp** [comment]
Can you update fixed on npm nodejs?

**Comment by fent** [comment]
Published new version.

**Comment by phongdaohp** [comment]
Thanks fent,

I have question for you. How can I handle error in process download avoid  crash my program?
Best regard.
