### ISSUE TITLE
stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by keithics** [fent/node-youtube-dl#67]
how can I increase the buffer size?
I got this when downloading a playlist.
``error 2: [Error: stdout maxBuffer exceeded.]``

**Comment by fent** [comment]
You can pass in the `maxBuffer` option in an object on the 3rd argument of to the downloading or getInfo() functions

https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback
