### ISSUE TITLE
Suggestion : spawn instead of execFile

### ISSUE THREAD

**Issue by jonathanasquier** [fent/node-youtube-dl#69]
I use node-youtube-dl to display videos in an express app. After a few calls callbacks are not executed anymore (read someting about pipes being full).
I made a very simple implementation with spawn that should have the same behaviour as execFile and that does not have the same issue:
```
var spawn = require('child_process').spawn;

var getRessource = function(url, callback) {
    var ytdl = spawn('youtube-dl', [url, '--get-url']),
    error = null,
    info = null;
	ytdl.stdout.on('data', function(data) {
		info = data.toString();
	});
	ytdl.stderr.on('data', function(data) {
		error = data.toString().slice(7);
	});
	ytdl.on('exit', function(code) {
		callback(error, info);
	});
};
```
I believe it's worth giving a shot.

Nice work ;)

**Comment by fent** [comment]
What error do you get with `execFile()`, if any? Because it is basically doing what your code above is doing.

**Comment by jonathanasquier** [comment]
Once I've launched my express API I make calls to the database in order to get for example Vimeo videos. I get a response once the video URL is extracted from node-youtube-dl. This works about 5 times, then I won't get any error/info callback from youtube-dl (maybe the child processes are hanging?). I'm not having this issue after stress testing with spawn.

**Comment by fent** [comment]
Are you executing the call sequentially or in parallel?

Also the code above doesn't concatenate the data.

**Comment by jonathanasquier** [comment]
Yes i'm not concatenating the data, this code is just a quick test I made. There is one call to youtube-dl per GET request on the Express API, so multiple child processes can be instanciated by multiple simultaneous calls.

If you believe it does not match node-youtube-dl's use cases you can close the issue :)

**Comment by fent** [comment]
That is one of its good cases, I'm just trying to figure out why `exec()` would be different than `spawn()` if we would be doing mostly the same thing `spawn()` does internally.

**Comment by jonathanasquier** [comment]
Yes, I have no idea why it would be different :/

**Comment by fent** [comment]
I attempted to test this
https://gist.github.com/fent/49c6ea13304d663e979e

but had no issues

**Comment by jonathanasquier** [comment]
I did too, with many more videos and it worked its hangs only when called
in express

**Comment by fent** [comment]
Only in express? Does express do something to child processes?

**Comment by jonathanasquier** [comment]
:/ I do not know!

**Comment by fent** [comment]
Can you reduce the error to a small file using express so I can test?

**Comment by jonathanasquier** [comment]
I did and It won't bug. I'm probably messing with something in my app that
breaks child processes, but still works with spawn!

2015-03-24 15:39 GMT+01:00 Roly Fentanes <notifications@github.com>:

**Comment by fent** [comment]
Update? I just can't justify changing this if it only works for one person. It's better to figure out why `spawn()` works if theoretically it would be doing the same thing but with code that's not as simple.
