### ISSUE TITLE
unable to extract comment count; please report this issue on http://yt-dl.org/bug

### ISSUE THREAD

**Issue by laggingreflex** [fent/node-youtube-dl#70]
Some sites aren't working. `youtube-dl` command line outputs a warning which shouldn't cause an error as it does output the json but node-youtube-dl does produce an error and doesn't create the `info` object. 

    python "C:\Users\...\AppData\Roaming\node_modules\youtube-dl\bin\youtube-dl" --dump-json  http://www.pornhub.com/view_video.php?viewkey=925419364 > json.js
    
gives the error

    WARNING: unable to extract comment count; please report this issue on http://yt-dl.org/bug

but it produces the json anyways which does contain the relevant stream url 

    {
        "display_id": "925419364",
        "extractor": "PornHub",
        "stitle": "Nicki Minaj - Anaconda (porn edit)",
        "format": "720P-1500K",
        ...
        "title": "Nicki Minaj - Anaconda (porn edit)",
        "url": "http://cdn2b.video.pornhub.phncdn.com/videos/201502/22/45224141/720P_1500K_45224141.mp4?rs=200&ri=2500&s=1427050269&e=1427057469&h=333057563d7ca8ffa781722dc75648e7",
        "extractor_key": "PornHub",
        ...
    }

but the outputed error is reproduced in node app and `info` object is null

    var video = youtubedl.getInfo(url,... function(err, info){
        // err => [Error: : unable to extract comment count; please report this issue on http://yt-dl.org/bug]
        // info => null
    }

**Comment by fent** [comment]
Can you give a video to test this on?

**Comment by laggingreflex** [comment]
http://www.pornhub.com/view_video.php?viewkey=925419364

**Comment by fent** [comment]
Ok now it just warns.

**Comment by laggingreflex** [comment]
Is this command

    python "C:\Users\...\AppData\Roaming\node_modules\youtube-dl\bin\youtube-dl" --dump-json  http://www.pornhub.com/view_video.php?viewkey=925419364 > json.js

not generating JSON for you? I know it shows the warning on console, but for me it also does generate the JSON, which has the stream URL..

**Comment by fent** [comment]
yeah it does. that's what the module does now too.
