### ISSUE TITLE
youtube-dl: error: no such option: --max-quality

### ISSUE THREAD

**Issue by przemyslawpluta** [fent/node-youtube-dl#74]
Looks like some updates are needed - https://github.com/przemyslawpluta/mongo-edu/issues/44 + https://github.com/rg3/youtube-dl/issues/5550

**Comment by fent** [comment]
Options changed in the youtube-dl binary, but no updates on this module are needed. Just update the options you were using.

**Comment by przemyslawpluta** [comment]
Agreed ... was thinking about the documentation.
