### ISSUE TITLE
Do you prefer to download bundled youtube-dl for windows ?

### ISSUE THREAD

**Issue by EragonJ** [fent/node-youtube-dl#81]
For my personal project, because it would be a big overhead to have python command for end users, I did update the code to make sure windows users can use bundled youtube-dl instead. Not sure this patch makes sense to you ?

**Comment by fent** [comment]
I would prefer if the binary was downloaded. It's updated very frequently and wouldn't want to update this every time they update.

**Comment by EragonJ** [comment]
Well, not sure what you mean. Right now for windows build, node-youtube-dl still downloads latest binary from the website but what I changed is to let it download the youtube-dl with python bundled. In this way, for users who use node-youtube-dl in windows, they don't have to be dependent on python.

What do you think ?

**Comment by fent** [comment]
I don't think it's a big deal to have to install python. This is meant for devs anyway, which will have likely done it already.

**Comment by EragonJ** [comment]
Well, I am fine with you decision, so mark this as closed.
