### ISSUE TITLE
Support autoupdate and extract downloader

### ISSUE THREAD

**Issue by EragonJ** [fent/node-youtube-dl#88]
Hi @przemyslawpluta , seems that you are the one who takes care of this project now.

I got some personal patches for

1. support autoupdate
2. extract downloader to make it callable as a library from caller

https://github.com/EragonJ/node-youtube-dl/commit/0cceb95b10743bb171164d708cc7aab385e41aa3
https://github.com/EragonJ/node-youtube-dl/commit/3524cb9496c6f55c8c7096f17eb824cea01b0645
https://github.com/EragonJ/Kaku/blob/master/src/modules/AutoUpdater.js#L109

Not sure whether you think these patches are reasonable or not. If you think these patches are fine, I can try to provide an updated patch for that. Thanks.

**Comment by endquote** [comment]
Auto-update would be cool. I currently do this via cron.

**Comment by EragonJ** [comment]
Looks like we got the first user - @endquote here ! The main idea here is to extract the download.js as a standalone ilb and caller can easily decide when to update your youtube-dl !

**Comment by endquote** [comment]
I'd definitely use that in my project (which isn't public, but I hope to open it in the coming weeks). This feature reminds me of a couple of things:

https://github.com/juliangruber/require-rebuild
https://github.com/remy/nodemon/blob/master/doc/requireable.md

**Comment by przemyslawpluta** [comment]
@EragonJ good idea. I'll have a look ...

**Comment by przemyslawpluta** [comment]
@EragonJ this should do it [downloader](https://github.com/fent/node-youtube-dl/blob/master/lib/downloader.js) not sure how do you want to implement autoupdate?

**Comment by EragonJ** [comment]
Nice, it seems that you did take part of my codes as reference to make a new downloader ! With standalone Downloader, developers can use that to do autoupdate. BTW, is it possible to add an options in Downloader to let us decide where to keep the binary ? (like this https://github.com/EragonJ/Kaku/blob/master/src/modules/AutoUpdater.js#L118) 

This is the only way that I can achieve the AutoUpdate feature in electron if the application is compressed under `asar` format.

**Comment by przemyslawpluta** [comment]
@EragonJ I've added an option to select different binary location. If not provided it will be dropped in default local `bin`.

```js
var downloader = require('../lib/downloader');
```

Default local path in `bin`
```js
downloader(function error(err, done) {
  'use strict';
  if (err) { return console.log(err.stack); }
  console.log(done);
});
```

Optional 'path/to-binary' 
```js
downloader('path/to-binary', function error(err, done) {
  'use strict';
  if (err) { return console.log(err.stack); }
  console.log(done);
});
```

After download / update absolute path to `binary` will be added to [package.json](https://github.com/fent/node-youtube-dl/blob/master/package.json) where [youtube-dl.js](https://github.com/fent/node-youtube-dl/blob/master/lib/youtube-dl.js#L9)
 will pick it up from.

Still considering if the path should be dropped into `package.json` or somewhere else.

**Comment by EragonJ** [comment]
oh coooool! I do like the optional path! The issue can be closed and I'll try to migrate from my own branch to this approach later and see whether there is any problem or no.

**Comment by przemyslawpluta** [comment]
@EragonJ let me know once tested on your side.

**Comment by EragonJ** [comment]
sure ! i'll ping yo later no matter it works or no. thanks man.
