### ISSUE TITLE
Better playlist documentation

### ISSUE THREAD

**Issue by aequasi** [fent/node-youtube-dl#90]
I'm trying to figure out how to download all the songs of a playlist, and the documentation is nonexistent, and the example, leaves a lot to be desired. 

Can i get a working example of downloading all the songs of a video, into a directory, and after they are all downloaded, doing something with the song info?

**Comment by aequasi** [comment]
Actually, after running the playlist example you have, it only downloads the first video

**Comment by pendo324** [comment]
I can confirm that the playlist example only downloads the first video

**Comment by przemyslawpluta** [comment]
@aequasi playlist is not fully functional there is no cue processing implemented yet.

**Comment by pendo324** [comment]
Until something is added to the library to parse playlists, this (rough) example with calls directly to the executable might help you out @aequasi 

    var getPlaylistUrls = function() {
        var playListJson;
        // the windows exe is just a version from the website with python prepackaged
        if (process.platform === "win32") {
            playListJson = exec.execFileSync("youtube-dl.exe", [url, "--flat-playlist", "-j"]);
        } else {
            playListJson = exec.execSync("python node_modules/youtube-dl/bin/youtube-dl " + url + " --flat-playlist -j");
        }
        
        // Remove the trailing \n
        var outString = playListJson.toString().replace(/\n$/, "").split("\n");
        var finalJsonString = "[";
        for (var entry in outString) {
            if (entry == outString.length - 1) {
                finalJsonString = finalJsonString + outString[entry] + "]";
            } else {
                finalJsonString = finalJsonString + outString[entry] + ",";
            }
        }
        var finalJson = JSON.parse(finalJsonString);
        //console.log(finalJson);

        var urls = [];
        // We don't want the deleted videos, since they can't be downloaded
        for (var video in finalJson) {
            if (finalJson[video].title !== "[Deleted Video]") {
                urls.push({
                    title: finalJson[video].title,
                    url: "http://www.youtube.com/watch?v=" + finalJson[video].url
                });
            }
        }
        console.log(urls);
    };

**Comment by aequasi** [comment]
Yeah, I've got something similar to that right now.

**Comment by przemyslawpluta** [comment]
@aequasi @pendo324 have a look at latest master this will handle playlist also example has been updated [playlist.js](https://github.com/fent/node-youtube-dl/blob/master/example/playlist.js)

ToDo
* [ ] playlist cleanup if video does not exist
