### ISSUE TITLE
how to get a list of all available video formats?

### ISSUE THREAD

**Issue by wdfsinap** [fent/node-youtube-dl#96]
hi, I can't find doc from your desc of how to get a list of all available video formats?
with youtuble-dl i can use youtube-dl --list-formats 'url' to get all availabe video formats, types, extension, resolution

**Comment by przemyslawpluta** [comment]
@wdfsinap `.getFormats` is deprecated use `.getInfo` instead. Just added example [formats.js](https://github.com/fent/node-youtube-dl/blob/master/example/formats.js)

**Comment by wdfsinap** [comment]
hi, can I get video urls together with video formats?
thanks

**Comment by przemyslawpluta** [comment]
@wdfsinap sure all the data is available in `info` based on example so just rewrite to your needs.

**Comment by wdfsinap** [comment]
thanks, i found it. but why some video gives undefined resolution?
{ itag: 'hls-460-1',
       filetype: 'mp4',
       resolution: undefined,
       url: 'https://proxy-81.dailymotion.com/sec(50643cb3d6ee57dd812906912c8df9fd)/video/996/554/221455699_mp4_h264_aac_6.m3u8#cell=core' },
     { itag: 'http-240',
       filetype: 'mp4',
       resolution: undefined,
       url: 'https://www.dailymotion.com/cdn/H264-320x240/video/x3nukb7.mp4?auth=1458160035-2562-guo3m220-28d4b5886aaf6b3b0de6a27cc6acca7e' },
     { itag: 'http-380',
       filetype: 'mp4',
       resolution: undefined,
       url: 'https://www.dailymotion.com/cdn/H264-512x384/video/x3nukb7.mp4?auth=1458160035-2562-13aivksq-17a4fba37fc624765bb4d88ec33fbfa9' } ] }

**Comment by wdfsinap** [comment]
i see some of video url are audio, can i get video urls only?
