### ISSUE TITLE
Resume Download with series of YT URIs

### ISSUE THREAD

**Issue by pquerner** [fent/node-youtube-dl#99]
My plan is to have an VOD Archive of my own of a youtubers videos. So when the script is called, it'll fetch a list of the youtubers videos and throw them at this library to download.

This works fine with a single video, but I struggle with the asynchron in node very hard. I do not come from that async background and dont really understand it yet.

Issues I currently have is

- how to determine file name when its a (possible) resume download. (I looked the example script resume.js and saw that the last line is the actual saving part, but I do fetch the filename of that video in a callback, so I have no idea about the filename at that time -> async)
- how to process a list of video ids (foreach), then throw them one by one at this library

Bugs are
- process list constantly shifts, I assume it'll download all videos simultaneously (havent checked). 

I can show the code, but its nowhere near complete nor beauty. I just throwed some things together in nano.

[Code to gist](https://gist.github.com/pquerner/752fe04c39a7061bfd09eab216779bc7)

Any help is appreciated.

**Comment by przemyslawpluta** [comment]
@pquerner can you please clean it up a bit and post link to gist.

**Comment by pquerner** [comment]
@przemyslawpluta I have added the link to gist like asked.

I think some problems are now solved
- grab the youtube video ids dynamically
- download an array of youtube ids

But
- it happens simultaneously still (the downloading process)
- it'll download videos all over again if called again (because it checks for {video_id}.mp4 which is renamed to {video_title}.mp4 and therefore cannot be found and is considered "not downloaded yet"  (I think I'll save the downloaded youtube ids in a database and query it to know whether I have downloaded the video yet or not)

**Comment by pquerner** [comment]
Well.. RTFM to me.

This does work just fine.

```
ytdl.exec('https://www.youtube.com/user/xxxx', ['--format', 'best', '--download-archive', __dirname + 'loaded'], {}, function(err, output) {
  if (err) throw err;
  console.log(output.join('\n'));
});
```
